GET http://localhost:8800/api/excuses/intro/get HTTP/1.1
###
GET http://localhost:8800/api/excuses/intro/get/6109bd2df6bfd213507d5d95 HTTP/1.1
###
POST http://localhost:8800/api/excuses/intro/create HTTP/1.1
Content-Type: application/json

{
  "title": "I know you're going to hate me but"
}

###
PUT http://localhost:8800/api/excuses/intro/edit/6109b32896800a0fe60c4b62 HTTP/1.1
Content-Type: application/json

{
  "title": "something wrong happened,sorry!"
}
###
DELETE  http://localhost:8800/api/excuses/intro/delete/6109afcba690090ec802bf1d HTTP/1.1

### DELAY
GET http://localhost:8800/api/excuses/delay/get HTTP/1.1

###
GET http://localhost:8800/api/excuses/delay/get/6109c0bd01554f13b010a581 HTTP/1.1
###
POST http://localhost:8800/api/excuses/delay/create HTTP/1.1
Content-Type: application/json

{
  "title": "stole my bicycle"
}
###
PUT http://localhost:8800/api/excuses/delay/edit/61278204995d6a2a625ab2ff HTTP/1.1
Content-Type: application/json

{
  "title": "won't stop telling me knock knock jokes"
}
###
DELETE  http://localhost:8800/api/excuses/delay/delete/6127823c995d6a2a625ab305 HTTP/1.1


// SCAPEGOAT \\

###
GET http://localhost:8800/api/excuses/scape-goat/get HTTP/1.1

###
GET http://localhost:8800/api/excuses/scape-goat/get/6109c272743f12141d859a42 HTTP/1.1
###
POST http://localhost:8800/api/excuses/scape-goat/create HTTP/1.1
Content-Type: application/json

{
  "title": "a professional cricket team"
}
###
PUT http://localhost:8800/api/excuses/scape-goat/edit/6109c280743f12141d859a44 HTTP/1.1
Content-Type: application/json

{
  "title": "something wrong RACLURE DE BIDET!"
}
###
DELETE  http://localhost:8800/api/excuses/scape-goat/delete/6109c272743f12141d859a42 HTTP/1.1
