GET http://localhost:8800/api/excuses/intro/get HTTP/1.1
###
GET http://localhost:8800/api/excuses/intro/get/6109bd2df6bfd213507d5d95 HTTP/1.1
###
POST http://localhost:8800/api/excuses/intro/create HTTP/1.1
Content-Type: application/json

{
  "title": "Please forgive my absence,"
}

###
PUT http://localhost:8800/api/excuses/intro/edit/6112e4721cf2f814573c41ce HTTP/1.1
Content-Type: application/json

{
  "title": "You will not believe me but,"
}
###
DELETE  http://localhost:8800/api/excuses/intro/delete/6109bd2df6bfd213507d5d95 HTTP/1.1


// SCAPEGOAT \\

###
GET http://localhost:8800/api/excuses/scape-goat/get HTTP/1.1

###
GET http://localhost:8800/api/excuses/scape-goat/get/6109c272743f12141d859a42 HTTP/1.1
###
POST http://localhost:8800/api/excuses/scape-goat/create HTTP/1.1
Content-Type: application/json

{
  "title": "a professional cricket team"
}
###
PUT http://localhost:8800/api/excuses/scape-goat/edit/611956e123bd3c4db2087435 HTTP/1.1
Content-Type: application/json

{
  "title": "a sad clown"
}
###
DELETE  http://localhost:8800/api/excuses/scape-goat/delete/6109c272743f12141d859a42 HTTP/1.1

### DELAY
GET http://localhost:8800/api/excuses/delay/get HTTP/1.1

###
GET http://localhost:8800/api/excuses/delay/get/6109c0bd01554f13b010a581 HTTP/1.1
###
POST http://localhost:8800/api/excuses/delay/create HTTP/1.1
Content-Type: application/json

{
  "title": "found me box of human teeth"
}
###
PUT http://localhost:8800/api/excuses/delay/edit/61278204995d6a2a625ab2ff HTTP/1.1
Content-Type: application/json

{
  "title": "won't stop telling me knock knock jokes"
}
###
DELETE http://localhost:8800/api/excuses/delay/delete/612803829dec084b5626feb6 HTTP/1.1


### Authentication
POST http://localhost:8800/api/register HTTP/1.1
Content-Type: application/json

{
  "username": "noussa bennacer",
  "email": "noussa@bennacer.com",
  "password": "password"
}

###

POST http://localhost:8800/api/login HTTP/1.1
Content-Type: application/json

{
  "email": "noussa@bennacer.com",
  "password": "password"
}

###

POST http://localhost:8800/api/forgotpassword HTTP/1.1
Content-Type: application/json

{
  "email": "mounir1@test.com",
  "password": "password123"
}

###

POST http://localhost:8800/api/resetpassword/hkKh97IUH HTTP/1.1
Content-Type: application/json

{
  "email": "mounir1@test.com",
  "password": "password123"
}
